// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Base: typeof import('./src/components/Base.vue')['default']
    BaseSettingsDrawer: typeof import('./src/components/BaseSettingsDrawer.vue')['default']
    DragTest: typeof import('./src/components/DragTest.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    PicList: typeof import('./src/components/PicList.vue')['default']
    PreviewWidget: typeof import('./src/components/PreviewWidget.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SeniorSettings: typeof import('./src/components/SeniorSettings.vue')['default']
    SideBar: typeof import('./src/components/SideBar.vue')['default']
    TextImageProcess: typeof import('./src/components/TextImageProcess.vue')['default']
    TopBar: typeof import('./src/components/TopBar.vue')['default']
    Wrapper: typeof import('./src/components/wrapper.vue')['default']
  }
}
