// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElInput: typeof import('element-plus/es')['ElInput']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    H222: typeof import('./src/components/H222.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Wrapper: typeof import('./src/components/Wrapper.vue')['default']
  }
}
