name: Release
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  release:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Node.js setup
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Rust setup
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install app dependencies and build web
        run: npm ci && node scripts/abuild.mjs
      - name: run npm mjs scripts
        run: |
          echo "ls ${{ github.workspace }}"
      - run: |
          ls ./src-tauri/winBin/
      - run: |
          ls ./src-tauri/darwinBin/

      - name: Build the app
        uses: tauri-apps/tauri-action@v0
        with:
          tagName: v__VERSION__ # tauri-action replaces \_\_VERSION\_\_ with the app version
          releaseName: "Watermark-Gui v__VERSION__"
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: false
          prerelease: true
