name: Release
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  release:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Node.js setup
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Rust setup
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: add aarch64-apple-darwin
        if: matrix.os == 'macos-latest'
        run: rustup target add aarch64-apple-darwin
      - name: Install app dependencies and build web
        run: npm ci && node scripts/abuild.mjs
      # - name: run npm mjs scripts
      #   run: |
      #     echo "ls ${{ github.workspace }}"
      # - run: |
      #     echo `pwd`
      # - run: |
      #     echo `ls ${{ github.workspace }}/src-tauri/winBin/`
      # - run: |
      #     echo `ls ${{ github.workspace }}/src-tauri/darwinBin/`

      - name: Build MacOS the app
        if: matrix.os == 'macos-latest'
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: --target universal-apple-darwin
          tagName: v__VERSION__ # tauri-action replaces \_\_VERSION\_\_ with the app version
          releaseName: "Watermark-Gui v__VERSION__"
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: false 
          prerelease: true 
      - name: Build Win-OS the app
        if: matrix.os == 'windows-latest'
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: v__VERSION__ # tauri-action replaces \_\_VERSION\_\_ with the app version
          releaseName: "Watermark-Gui v__VERSION__"
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: false 
          prerelease: true
